version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -f codebuild/Dockerfile-flask-codepipeline -t $IMAGE_REPO_NAME_FLASK .
      - docker tag $IMAGE_REPO_NAME_FLASK:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_FLASK:$IMAGE_TAG
      - docker build -f codebuild/Dockerfile-react-codepipeline -t $IMAGE_REPO_NAME_REACT .
      - docker tag $IMAGE_REPO_NAME_REACT:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_REACT:$IMAGE_TAG
      - docker build -f codebuild/Dockerfile-nginx-codepipeline -t $IMAGE_REPO_NAME_NGINX .
      - docker tag $IMAGE_REPO_NAME_NGINX:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_NGINX:$IMAGE_TAG
      - docker build -f codebuild/Dockerfile-mysql-codepipeline -t $IMAGE_REPO_NAME_MYSQL .
      - docker tag $IMAGE_REPO_NAME_MYSQL:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_MYSQL:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_FLASK:$IMAGE_TAG > imageDetail.json
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_REACT:$IMAGE_TAG >> imageDetail.json
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_NGINX:$IMAGE_TAG >> imageDetail.json
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME_MYSQL:$IMAGE_TAG >> imageDetail.json
      - aws ecs describe-task-definition --task-definition $TASK_FAMILY | jq '.taskDefinition | (.containerDefinitions[] | select(.name == "app") | .image) = "<APP_IMAGE>" | del(.taskDefinitionArn, .revision, .status, .requiresAttributes) ' > taskdef.json
      - sh -x codebuild/change_docker_compose.sh $IMAGE_REPO_NAME_FLASK $IMAGE_REPO_NAME_REACT $IMAGE_REPO_NAME_NGINX $IMAGE_REPO_NAME_MYSQL $AWS_ACCOUNT_ID
      - ls -al
      - sh -x codebuild/change_appspec.sh $TASK_FAMILY
      - cat appspec.yaml
artifacts:
  files:
    - appspec.yaml
    - imageDetail.json
    - taskdef.json
