version: "3.7"
services:
  flask-api:
    build:
      context: ./docker-images-flask
      dockerfile: Dockerfile
    ports:
      - 3031:3031
    volumes:
      - ./docker-images-flask:/var/www/
  nginx:
    build:
      context: ./docker-images-nginx
      dockerfile: Dockerfile
    volumes:
      - ./docker-images-nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-images-nginx/log:/var/log/nginx/
    links:
      - flask-api
    ports:
      - 5000:80
  react-client:
    build:
      context: ./docker-images-react
      dockerfile: Dockerfile
    volumes:
      - ./docker-images-react:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - nginx
    stdin_open: true
  mysql-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - TZ="Asia/Tokyo"
    ports:
      - 3306:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d # docker-entrypoint-initdb.d内のスクリプトは起動時に1度だけ実行される
