FROM python:3.8-buster

RUN mkdir /var/www
# workdirの指定
WORKDIR /var/www

COPY ./docker-images-flask .

# 依存Pythonライブラリインストール
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install cryptography

WORKDIR /var/www/src

CMD ["uwsgi","--ini","/var/www/uwsgi.ini"]